---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php7.4
    commands:
      - php -v
      - composer update
      - composer require phpmd/phpmd phpstan/phpstan
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache

  - name: phpcs
    image: joomlaprojects/docker-images:php7.4
    depends_on:
      - composer
    commands:
      - vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
      - vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/

  - name: phpmd
    image: joomlaprojects/docker-images:php7.4
    depends_on:
      - composer
    commands:
      - vendor/bin/phpmd src text cleancode
      - vendor/bin/phpmd src text codesize
      - vendor/bin/phpmd src text controversial
      - vendor/bin/phpmd src text design
      - vendor/bin/phpmd src text unusedcode
    failure: ignore

  - name: phpstan
    image: joomlaprojects/docker-images:php7.4
    depends_on:
      - composer
    commands:
      - vendor/bin/phpstan analyse src
    failure: ignore

  - name: phploc
    image: joomlaprojects/docker-images:php7.4
    depends_on:
      - composer
    commands:
      - phploc src
    failure: ignore

  - name: phpcpd
    image: joomlaprojects/docker-images:php7.4
    depends_on:
      - composer
    commands:
      - phpcpd src
    failure: ignore

  - name: deployment
    image: appleboy/drone-ssh
    depends_on:
      - phpcs
    settings:
      host:
        from_secret: framework_host
      username:
        from_secret: framework_username
      port: 22
      key:
        from_secret: ssh_key
      passphrase:
        from_secret: ssh_passphrase
      script:
        - cd /home/fwjoomla/siteData
        - bin/framework update:server
    when:
      branch:
        - master
      status:
        - success
      event:
        - push

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: ec24bd0a8a9ca401e2b8dc36805f9eb07c8603a3e892591e19e8b3e50f24a943

...
